# Generated by Django 5.0.4 on 2024-04-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='название')),
                ('short_description', models.CharField(max_length=35, verbose_name=' краткое описание')),
                ('full_description', models.TextField(verbose_name='полное описание')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('quantity', models.IntegerField(verbose_name='количество на складе')),
            ],
        ),
    ]
